name: ci
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
    - uses: actions/checkout@v3

    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v4

    - name: Install dependencies
      run: uv sync

    - name: Run mypy
      run: |
        uv run mypy .

    - name: Run Tests
      run: |
        uv run coverage run --branch -m pytest -vvv
        uv run coverage report
        uv run coverage xml

    - uses: codecov/codecov-action@v3
